# Generated by Django 3.1.14 on 2022-02-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agent_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('stops', models.IntegerField()),
                ('duration_mins', models.FloatField()),
                ('airline_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airline_id', to='flights.airline')),
                ('arrival_airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='flights.airport')),
                ('departure_airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('agent_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='flights.agent')),
                ('first_leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_leg', to='flights.leg')),
                ('second_leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_leg', to='flights.leg')),
            ],
        ),
    ]
